import {
  DashboardCalendarIcon,
  DashboardClockIcon,
  DashboardHouseIcon,
  DashboardListIcon,
  DashboardWarningIcon,
} from '../../icons/DashboardIcons';

export const SCHEDULING_STAT_CONFIGS = [
  {
    key: 'pending_approvals',
    label: 'Pending Approvals',
    valueKey: 'pending_approvals',
    Icon: DashboardClockIcon,
    iconColor: '#f59e0b',
    iconSize: 32,
    className: 'pending',
  },
  {
    key: 'total_rooms',
    label: 'Active Rooms',
    valueKey: 'total_rooms',
    Icon: DashboardHouseIcon,
    iconColor: '#3b82f6',
    iconSize: 32,
  },
  {
    key: 'active_time_slots',
    label: 'Time Slots',
    valueKey: 'active_time_slots',
    Icon: DashboardClockIcon,
    iconColor: '#8b5cf6',
    iconSize: 32,
  },
  {
    key: 'waitlist_entries',
    label: 'Waitlist Entries',
    valueKey: 'waitlist_entries',
    Icon: DashboardListIcon,
    iconColor: '#06b6d4',
    iconSize: 32,
  },
  {
    key: 'upcoming_bookings',
    label: 'Upcoming (7 Days)',
    valueKey: 'upcoming_bookings',
    Icon: DashboardCalendarIcon,
    iconColor: '#10b981',
    iconSize: 32,
  },
  {
    key: 'conflicts_today',
    label: 'Conflicts Today',
    valueKey: 'conflicts_today',
    Icon: DashboardWarningIcon,
    iconColor: '#ef4444',
    iconSize: 32,
    className: 'warning',
  },
];
