import { FaCalendarAlt, FaCheckCircle, FaHourglassHalf, FaThumbsUp } from 'react-icons/fa';

export const DASHBOARD_CARD_CONFIGS = [
  {
    key: 'total',
    label: 'Total Bookings',
    valueKey: 'total_bookings',
    Icon: FaCalendarAlt,
    iconColor: '#2563eb',
    iconSize: 24,
    change: 'Recorded',
    period: 'overall',
    duration: 0.5,
    fallback: 0,
  },
  {
    key: 'confirmed',
    label: 'Confirmed Reservation',
    valueKey: 'confirmed_bookings',
    Icon: FaCheckCircle,
    iconColor: '#059669',
    iconSize: 24,
    change: 'Current status',
    period: 'active',
    duration: 0.7,
    fallback: 0,
  },
  {
    key: 'approved',
    label: 'Approved Reservation',
    valueKey: 'approved_bookings',
    Icon: FaThumbsUp,
    iconColor: '#10b981',
    iconSize: 24,
    change: 'Resource utilization',
    period: 'ready',
    duration: 0.9,
    fallback: 0,
  },
  {
    key: 'pending',
    label: 'Pending Reservation',
    valueKey: 'pending_bookings',
    Icon: FaHourglassHalf,
    iconColor: '#f59e0b',
    iconSize: 24,
    change: 'Pending status',
    period: 'review',
    duration: 1.1,
    fallback: 0,
  },
];
