import { FaCalendarAlt, FaCheckCircle, FaHourglassHalf, FaThumbsUp } from 'react-icons/fa';

export const DASHBOARD_CARD_CONFIGS = [
  {
    key: 'total',
    label: 'Total Bookings',
    valueKey: 'total_bookings',
    Icon: FaCalendarAlt,
    iconColor: '#2563eb',
    iconSize: 24,
    change: 'neutral',
    period: 'All time',
    duration: 0.5,
    fallback: 0,
  },
  {
    key: 'confirmed',
    label: 'Confirmed',
    valueKey: 'confirmed_bookings',
    Icon: FaCheckCircle,
    iconColor: '#059669',
    iconSize: 24,
    change: '↑ Active',
    period: 'Current',
    duration: 0.7,
    fallback: 0,
  },
  {
    key: 'approved',
    label: 'Approved',
    valueKey: 'approved_bookings',
    Icon: FaThumbsUp,
    iconColor: '#10b981',
    iconSize: 24,
    change: '↑ Ready',
    period: 'To Use',
    duration: 0.9,
    fallback: 0,
  },
  {
    key: 'pending',
    label: 'Pending',
    valueKey: 'pending_bookings',
    Icon: FaHourglassHalf,
    iconColor: '#f59e0b',
    iconSize: 24,
    change: 'Awaiting',
    period: 'Review',
    duration: 1.1,
    fallback: 0,
  },
];
