# Generated by Django 6.0.1 on 2026-04-14 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("simulation", "0003_simulationauditlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="simulationresult",
            name="category_metrics",
            field=models.JSONField(
                blank=True,
                help_text="Category-specific data: peak_hours_data, shortage_impact, time_slot_breakdown, resource_combinations",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="simulationscenario",
            name="simulation_type",
            field=models.CharField(
                choices=[
                    ("room_usage", "Room Usage"),
                    ("equipment_usage", "Equipment Usage"),
                    ("peak_hour", "Peak Hour"),
                    ("shortage", "Shortage"),
                    ("what_if", "What-If Analysis"),
                    ("general", "General"),
                ],
                default="general",
                help_text="Category of simulation (room_usage, equipment_usage, peak_hour, shortage, what_if)",
                max_length=50,
            ),
        ),
    ]
