# Generated by Django 6.0.1 on 2026-01-30 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_equipment_waitlist_alter_booking_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='quantity',
            field=models.IntegerField(default=1, help_text='Total available quantity'),
        ),
        migrations.AlterField(
            model_name='room',
            name='equipment',
            field=models.ManyToManyField(blank=True, related_name='rooms_old', to='scheduling.equipment'),
        ),
        migrations.CreateModel(
            name='RoomEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, help_text='Quantity of this equipment in this room')),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_rooms', to='scheduling.equipment')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_equipment', to='scheduling.room')),
            ],
            options={
                'ordering': ['room__name', 'equipment__name'],
                'unique_together': {('room', 'equipment')},
            },
        ),
    ]
